//! aim-ai-case-archiver — CA1.
//!
//! When FE1 generates a regression eval case for a finding, that case
//! sits in `AIM_EVAL_CASES_DIR` forever. If subsequent diagnostics
//! never flag the same finding again, the bug is fixed and the case
//! is just noise. This crate moves such "resolved" cases into an
//! archive subdirectory so the active eval suite stays focused.
//!
//! Heuristic for "resolved":
//! - Case was generated by FE1 (id starts with `regr-`).
//! - Last K ledger reports do NOT contain the finding the case codified.
//! - Case is at least `min_age_days` old.
//!
//! Rust port of `AI/ai/case_archiver.py`.

use aim_ai_ledger::Ledger;
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum ArchiverError {
    #[error("ledger: {0}")]
    Ledger(#[from] aim_ai_ledger::LedgerError),
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Candidate {
    pub case_id: String,
    pub case_path: PathBuf,
    pub inferred_ref_path: String,
    pub inferred_ref_line: Option<u32>,
    pub age_days: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArchiveResult {
    pub n_candidates: u64,
    pub n_moved: u64,
    pub moved: Vec<PathBuf>,
    pub archive_dir: PathBuf,
}

#[derive(Debug, Clone)]
pub struct ArchiveOpts {
    pub lookback: u32,
    pub min_age_days: f64,
    pub dry_run: bool,
    pub cases_dir: Option<PathBuf>,
    pub archive_dir: Option<PathBuf>,
}

impl Default for ArchiveOpts {
    fn default() -> Self {
        Self {
            lookback: 7,
            min_age_days: 3.0,
            dry_run: false,
            cases_dir: None,
            archive_dir: None,
        }
    }
}

fn cases_dir(explicit: Option<&Path>) -> PathBuf {
    if let Some(p) = explicit {
        return p.to_path_buf();
    }
    if let Ok(s) = std::env::var("AIM_EVAL_CASES_DIR") {
        return PathBuf::from(s);
    }
    if let Ok(xdg) = std::env::var("XDG_CACHE_HOME") {
        return PathBuf::from(xdg).join("aim").join("eval_cases");
    }
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
    PathBuf::from(home).join(".cache").join("aim").join("eval_cases")
}

fn archive_dir(explicit: Option<&Path>, base_cases: &Path) -> PathBuf {
    if let Some(p) = explicit {
        return p.to_path_buf();
    }
    if let Ok(s) = std::env::var("AIM_EVAL_ARCHIVE_DIR") {
        return PathBuf::from(s);
    }
    base_cases.join("_archived")
}

/// Recover (slug, line) from a `regr-*` case id.
pub fn ref_from_id(case_id: &str) -> Option<(String, Option<u32>)> {
    use once_cell::sync::Lazy;
    use regex::Regex;
    static RE: Lazy<Regex> =
        Lazy::new(|| Regex::new(r"^regr-(?P<slug>[\w-]+?)(?:-l(?P<line>\d+))?$").unwrap());
    let caps = RE.captures(case_id)?;
    let slug = caps.name("slug")?.as_str().to_string();
    let line = caps.name("line").and_then(|m| m.as_str().parse().ok());
    Some((slug, line))
}

/// FE1's `_slug` heuristic: lowercase, non-alnum → `-`.
pub fn normalise_ref(r#ref: &str) -> (String, Option<u32>) {
    use once_cell::sync::Lazy;
    use regex::Regex;
    static RE: Lazy<Regex> = Lazy::new(|| Regex::new(r"[^a-z0-9]+").unwrap());
    let (path, line) = match r#ref.rsplit_once(':') {
        Some((p, l)) if l.chars().all(|c| c.is_ascii_digit()) => {
            (p.to_string(), l.parse::<u32>().ok())
        }
        _ => (r#ref.to_string(), None),
    };
    let slug = RE
        .replace_all(&path.to_lowercase(), "-")
        .trim_matches('-')
        .to_string();
    (slug, line)
}

fn findings_in_recent_reports(
    ledger: &Ledger,
    lookback: u32,
) -> Result<BTreeSet<(String, Option<u32>)>, ArchiverError> {
    let rows = ledger.recent(lookback as usize)?;
    let mut seen: BTreeSet<(String, Option<u32>)> = BTreeSet::new();
    for r in rows {
        let Some(p) = r.report_path else { continue };
        let path = Path::new(&p);
        if !path.exists() {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(path) else {
            continue;
        };
        for ref_str in aim_ai_meta_evaluator::parse_report(&text).findings {
            seen.insert(normalise_ref(&ref_str));
        }
    }
    Ok(seen)
}

fn age_days(p: &Path, now_secs: i64) -> f64 {
    let Ok(meta) = std::fs::metadata(p) else {
        return 0.0;
    };
    let Ok(modified) = meta.modified() else {
        return 0.0;
    };
    let mtime_secs = modified
        .duration_since(std::time::SystemTime::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0);
    let delta = (now_secs - mtime_secs).max(0) as f64;
    delta / 86400.0
}

pub fn candidates(
    ledger: &Ledger,
    opts: &ArchiveOpts,
) -> Result<Vec<Candidate>, ArchiverError> {
    let cases = cases_dir(opts.cases_dir.as_deref());
    if !cases.exists() {
        return Ok(Vec::new());
    }
    let seen = findings_in_recent_reports(ledger, opts.lookback)?;
    let now_secs = chrono::Utc::now().timestamp();
    let mut out: Vec<Candidate> = Vec::new();
    let pattern = format!("{}/regr-*.yaml", cases.display());
    let mut paths: Vec<PathBuf> = match glob::glob(&pattern) {
        Ok(it) => it.filter_map(Result::ok).collect(),
        Err(_) => Vec::new(),
    };
    paths.sort();
    for p in paths {
        let cid = match p.file_stem().and_then(|s| s.to_str()) {
            Some(s) => s.to_string(),
            None => continue,
        };
        let Some((slug, line)) = ref_from_id(&cid) else {
            continue;
        };
        let age = age_days(&p, now_secs);
        if age < opts.min_age_days {
            continue;
        }
        let key = (slug.clone(), line);
        if seen.contains(&key) {
            continue;
        }
        // For slug-only IDs, also reject if any seen ref shares the slug.
        if line.is_none() && seen.iter().any(|(s, _)| *s == slug) {
            continue;
        }
        out.push(Candidate {
            case_id: cid,
            case_path: p,
            inferred_ref_path: slug,
            inferred_ref_line: line,
            age_days: age,
        });
    }
    Ok(out)
}

pub fn archive(
    ledger: &Ledger,
    opts: &ArchiveOpts,
) -> Result<ArchiveResult, ArchiverError> {
    let cands = candidates(ledger, opts)?;
    let cases = cases_dir(opts.cases_dir.as_deref());
    let arch = archive_dir(opts.archive_dir.as_deref(), &cases);
    let mut moved: Vec<PathBuf> = Vec::new();
    if !opts.dry_run && !cands.is_empty() {
        std::fs::create_dir_all(&arch)?;
    }
    for c in &cands {
        let Some(name) = c.case_path.file_name() else {
            continue;
        };
        let target = arch.join(name);
        if opts.dry_run {
            moved.push(target);
            continue;
        }
        if let Err(e) = std::fs::rename(&c.case_path, &target) {
            tracing::warn!(error = ?e, path = %c.case_path.display(), "could not archive");
        } else {
            moved.push(target);
        }
    }
    Ok(ArchiveResult {
        n_candidates: cands.len() as u64,
        n_moved: moved.len() as u64,
        moved,
        archive_dir: arch,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use aim_ai_ledger::Ledger;
    use std::path::PathBuf;
    use tempfile::tempdir;

    fn fresh_ledger() -> (tempfile::TempDir, Ledger) {
        let d = tempdir().unwrap();
        let l = Ledger::open(d.path().join("ledger.db")).unwrap();
        (d, l)
    }

    #[test]
    fn ref_from_id_with_line() {
        let r = ref_from_id("regr-agents-foo-py-l42").unwrap();
        assert_eq!(r.0, "agents-foo-py");
        assert_eq!(r.1, Some(42));
    }

    #[test]
    fn ref_from_id_without_line() {
        let r = ref_from_id("regr-some-doc-md").unwrap();
        assert_eq!(r.0, "some-doc-md");
        assert_eq!(r.1, None);
    }

    #[test]
    fn ref_from_id_rejects_garbage() {
        assert!(ref_from_id("not-regr").is_none());
        assert!(ref_from_id("regr-").is_none());
    }

    #[test]
    fn normalise_ref_with_line() {
        let r = normalise_ref("agents/foo.py:42");
        assert_eq!(r.0, "agents-foo-py");
        assert_eq!(r.1, Some(42));
    }

    #[test]
    fn normalise_ref_without_line() {
        let r = normalise_ref("README.md");
        assert_eq!(r.0, "readme-md");
        assert_eq!(r.1, None);
    }

    #[test]
    fn empty_cases_dir_returns_no_candidates() {
        let d = tempdir().unwrap();
        let (_dl, ledger) = fresh_ledger();
        let opts = ArchiveOpts {
            cases_dir: Some(d.path().join("nope")),
            ..Default::default()
        };
        let cands = candidates(&ledger, &opts).unwrap();
        assert!(cands.is_empty());
    }

    #[test]
    fn young_case_not_archived() {
        let cases = tempdir().unwrap();
        // Make a brand-new regr- case
        let p = cases.path().join("regr-foo-py-l7.yaml");
        std::fs::write(&p, "id: regr-foo-py-l7\ntask: x\nrubrics:\n  min_length: 1\n")
            .unwrap();
        let (_dl, ledger) = fresh_ledger();
        let opts = ArchiveOpts {
            cases_dir: Some(cases.path().to_path_buf()),
            min_age_days: 1000.0,
            ..Default::default()
        };
        let cands = candidates(&ledger, &opts).unwrap();
        assert!(cands.is_empty(), "young case should be skipped");
    }

    #[test]
    fn old_case_with_no_recent_match_archived() {
        let cases = tempdir().unwrap();
        let p = cases.path().join("regr-old-py-l1.yaml");
        std::fs::write(&p, "id: regr-old-py-l1\ntask: x\nrubrics:\n  min_length: 1\n")
            .unwrap();
        // Backdate the file by 30 days using filetime crate? No — just
        // pass min_age_days = 0.0 in this test to bypass age filter.
        let (_dl, ledger) = fresh_ledger();
        let opts = ArchiveOpts {
            cases_dir: Some(cases.path().to_path_buf()),
            min_age_days: 0.0,
            ..Default::default()
        };
        let cands = candidates(&ledger, &opts).unwrap();
        assert_eq!(cands.len(), 1);
        assert_eq!(cands[0].case_id, "regr-old-py-l1");
    }

    #[test]
    fn case_skipped_when_recent_report_has_finding() {
        let cases_d = tempdir().unwrap();
        let reports_d = tempdir().unwrap();
        let case_path = cases_d.path().join("regr-agents-foo-py-l42.yaml");
        std::fs::write(
            &case_path,
            "id: regr-agents-foo-py-l42\ntask: x\nrubrics:\n  min_length: 1\n",
        )
        .unwrap();

        // Write a report that names the same finding
        let report = reports_d.path().join("r.md");
        std::fs::write(&report, "issue at agents/foo.py:42").unwrap();
        let (_dl, ledger) = fresh_ledger();
        ledger
            .record(
                "m",
                Some("A"),
                0,
                0,
                None,
                None,
                None,
                None,
                false,
                Some(report.to_str().unwrap()),
                Some("2026-05-04T00:00:00Z"),
            )
            .unwrap();

        let opts = ArchiveOpts {
            cases_dir: Some(cases_d.path().to_path_buf()),
            min_age_days: 0.0,
            ..Default::default()
        };
        let cands = candidates(&ledger, &opts).unwrap();
        assert!(cands.is_empty(), "still-flagged finding must keep its case");
    }

    #[test]
    fn archive_dry_run_does_not_move_file() {
        let cases_d = tempdir().unwrap();
        let archive_d: PathBuf = cases_d.path().join("_archived");
        let p = cases_d.path().join("regr-x-py-l1.yaml");
        std::fs::write(
            &p,
            "id: regr-x-py-l1\ntask: x\nrubrics:\n  min_length: 1\n",
        )
        .unwrap();
        let (_dl, ledger) = fresh_ledger();
        let opts = ArchiveOpts {
            cases_dir: Some(cases_d.path().to_path_buf()),
            archive_dir: Some(archive_d.clone()),
            min_age_days: 0.0,
            dry_run: true,
            ..Default::default()
        };
        let r = archive(&ledger, &opts).unwrap();
        assert_eq!(r.n_candidates, 1);
        assert_eq!(r.n_moved, 1);
        assert!(p.exists(), "dry_run must not move the file");
        assert!(!archive_d.exists() || archive_d.read_dir().unwrap().count() == 0);
    }

    #[test]
    fn archive_real_moves_file() {
        let cases_d = tempdir().unwrap();
        let archive_d: PathBuf = cases_d.path().join("_archived");
        let p = cases_d.path().join("regr-x-py-l1.yaml");
        std::fs::write(
            &p,
            "id: regr-x-py-l1\ntask: x\nrubrics:\n  min_length: 1\n",
        )
        .unwrap();
        let (_dl, ledger) = fresh_ledger();
        let opts = ArchiveOpts {
            cases_dir: Some(cases_d.path().to_path_buf()),
            archive_dir: Some(archive_d.clone()),
            min_age_days: 0.0,
            dry_run: false,
            ..Default::default()
        };
        let r = archive(&ledger, &opts).unwrap();
        assert_eq!(r.n_moved, 1);
        assert!(!p.exists(), "source must be gone");
        assert!(archive_d.join("regr-x-py-l1.yaml").exists());
    }
}
